### ISSUE TITLE
BUG: API not starting due Employee Schema not found

### ISSUE THREAD

**Issue by viniciusaito** [viniciusaito/cineclub_6sem#11]
/mnt/c/Users/ViniciusSaitoSilva/Desktop/pi_6sem/nodejs_api/node_modules/mongoose/lib/index.js:490
      throw new mongoose.Error.MissingSchemaError(name);
      ^
MissingSchemaError: Schema hasn't been registered for model "Employee".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/mnt/c/Users/ViniciusSaitoSilva/Desktop/pi_6sem/nodejs_api/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at Mongoose.model (/mnt/c/Users/ViniciusSaitoSilva/Desktop/pi_6sem/nodejs_api/node_modules/mongoose/lib/index.js:490:13)
    at Object.<anonymous> (/mnt/c/Users/ViniciusSaitoSilva/Desktop/pi_6sem/nodejs_api/src/controllers/EmployeeController.js:3:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/ViniciusSaitoSilva/Desktop/pi_6sem/nodejs_api/src/routes.js:6:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by viniciusaito** [comment]
solved, it was an error on requiring the models on server.js
